name: Docker Build CI

on:
  push:
    branches:
      - develop
      - master
      - 1.*
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v2
